### ISSUE TITLE
Dependent encutils will not work in Python 3.13

### ISSUE THREAD

**Issue by selfboot** [jaraco/cssutils#33]
`encutils` is too old and doesn't look like it's being maintained, so consider switching to another library

```
encutils/__init__.py:55: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
    import cgi

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

**Comment by selfboot** [comment]
It seems that no one is maintaining this project anymore, so I have deprecated cssutils in my own project.

**Comment by APN-Pucky** [comment]
This commit removed cgi already https://github.com/jaraco/cssutils/commit/9d69993c581e2b3c2332524998136c88f122e96c. `encutils` is a part of cssutils and the latest version `2.7.1` no longer gives that warning.

**Comment by jaraco** [comment]
What makes you think it isn't being maintained? At the time you posted this bug, the most recent commit was less than 2 months old (7a6910ca54e480e9a2b3585ed3e751f51e9bdd3a). Python 3.13 isn't due to be released until October 2024.

Since I maintain hundreds of projects in the ecosystem, I only check in on projects periodically, but one of my top priorities is to make sure that these projects continue to run on the latest supported Pythons.
